packages:
  - pkgs/*
  - pkgs/tz/test/engines

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
